{{- if and .Values.route.enabled "true" -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ include "deploypackage.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ .Values.appname }}
    weight: 100
  port:
    targetPort: {{ .Values.route.targetServicePort }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: {{ .Values.route.tls.wildcardPolicy }}
{{- end }}
