apiVersion: v1
entries:
  deployment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-08T17:22:04.191223308+03:00"
    description: A Helm chart for Kubernetes
    digest: e9db05761476d36d5f007f1dff224d657ac401e5782eaa1b2a5c4754c38eea4b
    name: deployment
    type: application
    urls:
    - https://oktaysavdi.github.io/helm/charts/deployment-0.1.0.tgz
    version: 0.1.0
generated: "2022-03-08T17:22:04.188862573+03:00"
